home_finder_app/home_finder_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^homesapp/', include('homesapp.urls')),
]

home_finder_app/homesapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .import views


urlpatterns = [
    # /homesapp/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /homesapp/1
    url(r'^(?P<pk>[0-9])/$', views.LocationView.as_view(), name='property'),

    # /homesapp/1/2
    url(r'^([0-9]+)/(?P<pk>[0-9]+)/$', views.PropertyDetail.as_view(), name='propertyview'),
]

home_finder_app/homesapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Location(models.Model):
    location_name = models.CharField(max_length = 200)
    location_type = models.CharField(max_length = 200)

    def __str__(self):
        return self.location_name

class Property(models.Model):
    location = models.ForeignKey(Location, on_delete = models.CASCADE)
    property_name = models.CharField(max_length = 200)
    area = models.CharField(max_length = 200)
    age = models.CharField(max_length = 200)
    price = models.CharField(max_length = 200)
    direction = models.CharField(max_length = 200)
    floors = models.CharField(max_length = 200)
    postdd = models.CharField(max_length = 200)
    image_url = models.CharField(max_length = 500)
    lat_field = models.CharField(max_length = 200)
    long_field = models.CharField(max_length = 200)

    def __str__(self):
        return self.property_name

home_finder_app/homesapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic
from .models import Location, Property

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'homesapp/index.html'

    def get_queryset(self):
        return Location.objects.all()

class LocationView(generic.DetailView):
    model = Location
    template_name = 'homesapp/locationview.html'

class LocationView(generic.DetailView):
    model = Location
    template_name = 'homesapp/locationview.html'

class PropertyDetail(generic.DetailView):
    model = Property
    template_name = 'homesapp/propertyview.html'

home_finder_app/homesapp/templates/homesapp/base.html
<html>
    <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">    
            <a class="navbar-brand" href="#">Homesapp</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Page 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Page 2</a>
                </li>
            </ul>
            <ul class="navbar-nav nav-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Log In</a>
                    </li>
                </ul>
            </div>

        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

home_finder_app/homesapp/templates/homesapp/index.html
{% extends 'homesapp/base.html' %}


{% block body %}
{% for location in object_list %}
<a href="/homesapp/{{location.id}}">{{location.location_name}}</a>
<br>
{% endfor %}
{% endblock %}

home_finder_app/homesapp/templates/homesapp/locationview.html
{% extends 'homesapp/base.html' %}


{% block body %}

<html>
    <head>
    </head>
    <body>
        <div class="containter-fluid">
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-8">
                    <h1>Properties in {{ location.location_name }}</h1>
                    {% for place in location.property_set.all %}
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <a>{{ place.property_name }}</a>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ place.image_url }}" height="200" width="200">
                                </div>
                                <div class"col-md-6">
                                    <table class='table'>
                                        <tr>
                                            <td>
                                                <label><b>Area SQFT</b></label>
                                            </td>
                                            <td>
                                                {{ place.area }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>Price</b></label>
                                            </td>
                                            <td>
                                                {{ place.price }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>Floors</b></label>
                                            </td>
                                            <td>
                                                {{ place.floors }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>Zip</b></label>
                                            </td>
                                            <td>
                                                {{ place.postdd }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>
                                                <a class="btn btn-success" href='/homesapp/{{location.id}}/{{place.id}}'>
                                                    View Details
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </body>
</html>


{% endblock %}

home_finder_app/homesapp/templates/homesapp/propertyview.html
{% extends "homesapp/base.html" %}

{% block body %}

<!-- Need to write code to get lat and long from home zip code -->

<html>
    <head>
        <style>
            /* Set the size of the div element that contains the map */
            #map {
                height: 400px;  /* The height is 400 pixels */
                width: 100%;  /* The width is the width of the web page */
            }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-3">
                <div class="img-thumbnail">
                    <img src="{{property.image_url}}" height="300" width="300">
                    <div class="caption">
                        <p>{{ property.property_name }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="container">
                    <div class="card">
                        <div class="card-header bg-primary text-white">Property Details</div>
                    </div>
                    <div class="card-body">
                        <table class='table'>
                            <tr>
                                <td>
                                    <label><b>Area SQFT</b></label>
                                </td>
                                <td>
                                    {{ property.area }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label><b>Area SQFT</b></label>
                                </td>
                                <td>
                                    {{ property.area }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label><b>Property Age</b></label>
                                </td>
                                <td>
                                    {{ property.age }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label><b>Price</b></label>
                                </td>
                                <td>
                                    {{ property.price }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label><b>Direction Facing</b></label>
                                </td>
                                <td>
                                    {{ property.direction }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label><b>Floors</b></label>
                                </td>
                                <td>
                                    {{ property.floors }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label><b>Zip</b></label>
                                </td>
                                <td>
                                    {{ property.postdd }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    <!-- map code -->
        <div class="col-md-8">
            <div class="thumbnail">
                <h3>Location</h3> 
                <div id="map"></div>
                <script>
                    // Initialize and add the map
                    function initMap() {
                    // The location of Uluru
                    var uluru = {lat: {{ property.lat_field }}, lng: {{ property.long_field }}};
                    // The map, centered at Uluru
                    var map = new google.maps.Map(
                        document.getElementById('map'), {zoom: 4, center: uluru});
                    // The marker, positioned at Uluru
                    var marker = new google.maps.Marker({position: uluru, map: map});
                    }
                </script>
                <!--Load the API from the specified URL
                * The async attribute allows the browser to render the page while the API loads
                * The key parameter will contain your own API key (which is not needed for this tutorial)
                * The callback parameter executes the initMap() function
                -->
                <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">
                </script>
            </div>
        </div>
    </body>
</html>

{% endblock %}