todo/todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # routes to todoapp folder and file
    url(r'^todoapp/', include('todoapp.urls')),
]

todo/todoapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


app_name = 'todoapp'
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

todo/todoapp/models.py
from django.db import models

# Create your models here.
# models for the db


class Task(models.Model):

    def __str__(self):
        return self.task_name

    task_name = models.CharField(max_length=200)
    task_priority = models.CharField(max_length=200)

todo/todoapp/views.py
from django.views import generic
from .models import Task

class IndexView(generic.ListView):
    template_name = 'todoapp/index.html'

    def get_queryset(self):
        return Task.objects.all()

class DetailView(generic.DetailView):
    model = Task
    template_name = 'todoapp/detail.html'

todo/todoapp/templates/todoapp/base.html
{% load staticfiles %}
<!-- Need to add buttons to create a task, delete task, maybe category lists view -->
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'todoapp/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/todoapp/">My Todo App</a>
                <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Item 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Item 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Item 3</a>
                        </li>
                    </ul>
                    
                </div> -->
            </div>
        </nav>

        {% block body %}
        {% endblock %}
    </body>
</html>

todo/todoapp/templates/todoapp/detail.html
{% extends 'todoapp/base.html' %}

{% block body %}

        <div class="container">
            <h2>Task</h2>
            <table class='table'>
                <thead>
                    <tr>
                        <th>Task Name</th>
                        <th>Task Priority</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class='active'>
                        <td>
                            <a>{{ task.task_name }}</a>
                        </td>
                        <td>
                            <a>{{ task.task_priority }}</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        {% endblock %}

todo/todoapp/templates/todoapp/index.html
{% extends 'todoapp/base.html' %}

<html>
    <head>
    </head>
    <body>

        {% block body %}

        <div class="container">
            <h2>Today's List</h2>
            <table class='table'>
                <thead>
                    <tr>
                        <th>Task Name</th>
                        <th>Task Priority</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% if task_list %}
                        {% for task in object_list %}
                        <tr class='active'>
                            <td>
                                <a href="{% url 'todoapp:detail' task.id %}">{{ task.task_name }}</a>
                            </td>
                            <td>
                                <b>{{task.task_priority}}</b>
                            </td>
                            <td>
                                <button type='button' class='btn btn-primary'>Done</button>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                    {% endif %}

                </tbody>
            </table>
        </div>

        {% endblock %}
    </body>
</html>